auth_example/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("hyperion.urls")),
    path("users/", include("users.urls")),
]

hyperion/urls.py
from django.urls import path
from . import views

app_name = "hyperion"
urlpatterns = [
	path("", views.home, name="home"),
	path("about/", views.about, name="about"),
	path("blog/<int:pk>", views.blog, name="blog")
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

app_name = "users"
urlpatterns = [
	path("login/", LoginView.as_view(), name="login"),
	path("register/", views.register, name="register"),
]

hyperion/models.py
from django.db import models


# Create your models here.
class Band(models.Model):
	name = models.CharField(max_length=100)
	album = models.CharField(max_length=100)
	year_of_origin = models.IntegerField()

	def __str__(self):
		return self.name

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserRegistrationForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'password1', 'password2']

hyperion/views.py
from django.shortcuts import render
from . models import Band
from django.contrib.auth.decorators import login_required


def home(request):
	all_blogs = Band.objects.all()
	return render(
		request,
		"hyperion/home.html",
		{"blogs": all_blogs}
	)


def about(request):
	return render(request, "hyperion/about.html")


@login_required()
def blog(request, pk):
	selected_blog = Band.objects.get(pk=pk)
	return render(
		request,
		"hyperion/blog.html",
		{"blog": selected_blog}
	)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from . forms import UserRegistrationForm


def register(request):
	if request.method == "POST":
		form = UserRegistrationForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			return redirect("hyperion:home")
	else:
		form = UserRegistrationForm()
	return render(
		request,
		"registration/register.html",
		{"form": form}
	)

hyperion/templates/hyperion/about.html
{% extends "base.html" %}
{% block content %}
    <h1>This is the about page!</h1>
{% endblock %}

hyperion/templates/hyperion/blog.html
{% extends "base.html" %}
{% block content %}
    <h3>{{ blog.name }}</h3>
    <p>{{ blog.album }}</p>
    <p>{{ blog.year_of_origin }}</p>
{% endblock %}

hyperion/templates/hyperion/home.html
{% extends "base.html" %}
{% block content %}
    <h1>All Blogs</h1>
    <ul>
        {% for blog in blogs %}
            <li><a href="{% url 'hyperion:blog' blog.id %}" class="submit-btn">{{ blog.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Music Database</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header>
        <h1>Welcome to the Music Database</h1>
        <nav>
            <ul>
                <li><a href="{% url 'hyperion:home' %}">Home</a></li>
                <li><a href="{% url 'hyperion:about' %}">About</a></li>
                <li><a href="{% url 'users:login' %}">Log In</a></li>
                <li><a href="{% url 'users:register' %}">Register</a></li>
            </ul>
        </nav>
    </header>
    {% block content %}{% endblock %}
</body>